# config/app.yml for rails-settings-cached
defaults: &defaults
  deploying: false
  pending: false
  cancel: <%= Time.current %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
