# Configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:concurrency: 4
:timeout: 25
test:
  :pidfile: tmp/pids/sidekiq.pid
  :verbose: false
  :queues:
    - default
development:
  :pidfile: tmp/pids/sidekiq.pid
  :verbose: false
  :queues:
    - default
production:
  :pidfile: tmp/pids/sidekiq.pid
  :verbose: true
  :queues:
    - default
